/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders } from '@angular/common/http';

import { Observable } from 'rxjs';

import { AvailableTablesDto } from '../model/models';
import { DatabaseConnectionData } from '../model/models';
import { GenerationRequestDto } from '../model/models';

import { Configuration } from '../configuration';

export interface CrudGeneratorControllerServiceInterface {
  defaultHeaders: HttpHeaders;
  configuration: Configuration;

  /**
   *
   *
   * @param generationRequest
   * @param databaseConnectionData
   */
  generateProject(
    generationRequest: GenerationRequestDto,
    databaseConnectionData: DatabaseConnectionData,
    extraHttpRequestParams?: any
  ): Observable<object>;

  /**
   *
   *
   * @param databaseConnectionData
   */
  getAvailableTables(
    databaseConnectionData: DatabaseConnectionData,
    extraHttpRequestParams?: any
  ): Observable<AvailableTablesDto>;
}
